
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-14T13:50:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a32ddc64a5f73117f51c6da48b92020b33c0a159",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
