# Generated by Django 3.2.23 on 2025-03-07 12:56

from django.db import (
    migrations,
)

from concentrator.smev3_v321.esnsi.classifiers import (
    ChildrenOrganizationClassifier,
)


def forwards(apps, schema_editor):
    """Добавление типа справочника "Органы управления образованием"."""

    ESNSIClassifier = apps.get_model('smev3_v321', 'ESNSIClassifier')

    ESNSIClassifier.objects.get_or_create(
        name=ChildrenOrganizationClassifier.__doc__, classifier_class=ChildrenOrganizationClassifier.__name__
    )


def backwards(apps, schema_editor):
    """Удаляем добавленный тип справочника."""

    ESNSIClassifier = apps.get_model('smev3_v321', 'ESNSIClassifier')

    ESNSIClassifier.objects.filter(classifier_class=ChildrenOrganizationClassifier.__name__).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('smev3_v4', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
