"""Actions."""

ES_ACTIONS = [
    "aprender algo nuevo sobre",
    "explorar más sobre",
    "compartir ideas sobre",
    "disfrutar un momento con",
    "dedicar tiempo a",
    "encontrar nuevas formas de entender",
    "admirar la belleza de",
    "apreciar el arte de",
    "profundizar en el conocimiento de",
    "inspirarme con historias sobre",
    "colaborar en proyectos de",
    "descubrir el impacto de",
    "crear algo especial relacionado con",
    "motivar a otros a explorar sobre",
    "recordar lo importante de",
    "aprovechar cada momento con",
    "dejarme llevar por la pasión por",
    "tomar un nuevo enfoque hacia",
    "iniciar una conversación sobre",
    "comprometerme más con",
    "imaginar nuevas posibilidades con",
    "involucrarme más en la comunidad de",
    "transformar mi perspectiva sobre",
    "apoyar iniciativas relacionadas con",
    "divertirme explorando sobre",
    "innovar en proyectos relacionados con",
    "compartir mi experiencia sobre",
    "aprender de los demás sobre",
    "ser parte de algo más grande relacionado con",
    "celebrar los logros en",
]
"""Spanish actions."""

EN_ACTIONS = [
    "learning something new about",
    "exploring more about",
    "sharing ideas about",
    "enjoying a moment with",
    "dedicating time to",
    "finding new ways to understand",
    "admiring the beauty of",
    "appreciating the art of",
    "deepening my knowledge of",
    "being inspired by stories about",
    "collaborating on projects about",
    "discovering the impact of",
    "creating something special related to",
    "motivating others to explore about",
    "remembering the importance of",
    "making the most of every moment with",
    "letting myself be driven by passion for",
    "taking a new approach to",
    "starting a conversation about",
    "committing more to",
    "imagining new possibilities with",
    "getting more involved in the community of",
    "transforming my perspective on",
    "supporting initiatives related to",
    "having fun exploring about",
    "innovating in projects related to",
    "sharing my experience about",
    "learning from others about",
    "being part of something bigger related to",
    "celebrating achievements in",
]
"""English actions."""

FR_ACTIONS = [
    "apprendre quelque chose de nouveau sur",
    "explorer davantage sur",
    "partager des idées sur",
    "profiter d'un moment avec",
    "consacrer du temps à",
    "trouver de nouvelles façons de comprendre",
    "admirer la beauté de",
    "apprécier l'art de",
    "approfondir mes connaissances sur",
    "m'inspirer des histoires sur",
    "collaborer sur des projets concernant",
    "découvrir l'impact de",
    "créer quelque chose de spécial lié à",
    "motiver les autres à explorer sur",
    "me rappeler l'importance de",
    "profiter au maximum de chaque moment avec",
    "me laisser guider par la passion pour",
    "adopter une nouvelle approche de",
    "commencer une conversation sur",
    "m'engager davantage dans",
    "imaginer de nouvelles possibilités avec",
    "m'impliquer davantage dans la communauté de",
    "transformer ma perspective sur",
    "soutenir des initiatives liées à",
    "m'amuser en explorant sur",
    "innover dans des projets liés à",
    "partager mon expérience sur",
    "apprendre des autres sur",
    "faire partie de quelque chose de plus grand concernant",
    "célébrer les réussites dans",
]
"""French actions."""

DE_ACTIONS = [
    "etwas Neues lernen über",
    "mehr erforschen über",
    "Ideen austauschen über",
    "einen Moment genießen mit",
    "Zeit widmen für",
    "neue Wege finden zum Verstehen von",
    "die Schönheit bewundern von",
    "die Kunst wertschätzen von",
    "mein Wissen vertiefen über",
    "mich inspirieren lassen von Geschichten über",
    "an Projekten mitarbeiten über",
    "die Auswirkung entdecken von",
    "etwas Besonderes schaffen in Bezug auf",
    "andere motivieren zum Erkunden von",
    "mich erinnern an die Wichtigkeit von",
    "jeden Moment optimal nutzen mit",
    "mich von der Leidenschaft leiten lassen für",
    "einen neuen Ansatz finden für",
    "ein Gespräch beginnen über",
    "mich mehr engagieren für",
    "neue Möglichkeiten vorstellen mit",
    "mich mehr in der Gemeinschaft einbringen von",
    "meine Perspektive verändern auf",
    "Initiativen unterstützen in Bezug auf",
    "Spaß haben beim Erkunden von",
    "in Projekten innovativ sein bezüglich",
    "meine Erfahrung teilen über",
    "von anderen lernen über",
    "Teil von etwas Größerem sein in Bezug auf",
    "Erfolge feiern in",
]
"""German actions."""

ACTIONS = {
    'es': ES_ACTIONS,
    'en': EN_ACTIONS,
    'fr': FR_ACTIONS,
    'de': DE_ACTIONS,
}
"""Actions by language."""
