"""Comments."""

ES_COMMENTS = [
    "Me encanta todo lo relacionado con {topic}. ¡Siempre hay algo nuevo por descubrir!",
    "{topic} es uno de mis temas favoritos. ¿Qué opinas tú?",
    "Nunca pensé que {topic} pudiera ser tan interesante. ¡Gracias por compartir!",
    "Tengo curiosidad por aprender más sobre {topic}. ¿Tienes alguna recomendación?",
    "{topic} siempre logra inspirarme de alguna manera. Es fascinante.",
    "Increíble cómo {topic} puede conectar a tantas personas. ¡Es genial!",
    "Estoy empezando a interesarme mucho por {topic}. Gracias por motivarme a explorarlo.",
    "Sin duda, {topic} es un tema que merece más atención. ¡Muy bien dicho!",
    "Cada vez que leo algo sobre {topic}, aprendo algo nuevo. ¡Gracias!",
    "¿Sabías que {topic} tiene un impacto tan grande? Me encantaría saber más.",
    "No puedo creer lo mucho que disfruté de {topic}. ¡Estoy emocionado!",
    "A veces me pregunto cuánto podemos aprender de {topic}. ¡Es interesante!",
    "Cada vez que veo algo sobre {topic}, me siento inspirado. ¡Gracias por compartir!",
    "Me encanta cómo {topic} siempre tiene algo nuevo que ofrecer. ¡Es increíble!",
    "Es fascinante ver cómo {topic} evoluciona constantemente. ¡Qué emocionante!",
    "Siempre he querido aprender más sobre {topic}. Esto me motiva aún más.",
    "{topic} es un tema que une a las personas. ¡Eso es lo que más me gusta!",
    "Cada detalle sobre {topic} me parece fascinante. ¡Es una fuente de inspiración!",
    "Gracias por mostrarme una nueva perspectiva sobre {topic}. ¡Muy interesante!",
    "Leer sobre {topic} siempre mejora mi día. ¡Es increíble lo que se puede aprender!",
    "Nunca me canso de descubrir cosas nuevas sobre {topic}. ¡Siempre hay algo interesante!",
    "Qué asombroso es ver cómo {topic} puede impactar tantas vidas. ¡Inspirador!",
    "Gracias a {topic}, he descubierto una nueva pasión. ¡Qué emocionante!",
    "Es impresionante lo que podemos lograr cuando hablamos de {topic}. ¡Gran tema!",
    "¿Quién iba a pensar que {topic} podría ser tan motivador? ¡Gracias por compartir!",
    "El mundo de {topic} nunca deja de sorprenderme. ¡Siempre hay algo fascinante!",
    "Cuando pienso en {topic}, me siento lleno de entusiasmo. ¡Qué tema tan genial!",
    "Definitivamente, {topic} tiene un potencial enorme. ¡No puedo esperar para aprender más!",
    "Cada conversación sobre {topic} me deja algo nuevo para reflexionar. ¡Es increíble!",
    "No hay límites para lo que podemos aprender de {topic}. ¡Me encanta este tema!",
]
"""Spanish comments."""

EN_COMMENTS = [
    "I love everything about {topic}. There's always something new to discover!",
    "{topic} is one of my favorite topics. What do you think?",
    "I never thought {topic} could be so interesting. Thanks for sharing!",
    "I'm curious to learn more about {topic}. Do you have any recommendations?",
    "{topic} always manages to inspire me in some way. It's fascinating.",
    "It's amazing how {topic} can connect so many people. That's awesome!",
    "I'm starting to take a real interest in {topic}. Thanks for motivating me to explore it.",
    "Without a doubt, {topic} is a topic that deserves more attention. Well said!",
    "Every time I read something about {topic}, I learn something new. Thanks!",
    "Did you know {topic} has such a big impact? I'd love to learn more.",
    "I can't believe how much I enjoyed {topic}. I'm so excited!",
    "Sometimes I wonder how much we can learn from {topic}. It's so interesting!",
    "Every time I see something about {topic}, I feel inspired. Thanks for sharing!",
    "I love how {topic} always has something new to offer. It's amazing!",
    "It's fascinating to see how {topic} constantly evolves. So exciting!",
    "I've always wanted to learn more about {topic}. This motivates me even more.",
    "{topic} is a topic that brings people together. That's what I love most!",
    "Every detail about {topic} is fascinating to me. It's such a source of inspiration!",
    "Thank you for showing me a new perspective on {topic}. Very interesting!",
    "Reading about {topic} always makes my day better. It's amazing what we can learn!",
    "I never get tired of discovering new things about {topic}. There's always something intriguing!",
    "How amazing it is to see how {topic} can impact so many lives. Inspirational!",
    "Thanks to {topic}, I've discovered a new passion. How exciting!",
    "It's impressive what we can achieve when we talk about {topic}. Great topic!",
    "Who would have thought that {topic} could be so motivating? Thanks for sharing!",
    "The world of {topic} never ceases to amaze me. There's always something fascinating!",
    "When I think about {topic}, I feel so enthusiastic. What a cool topic!",
    "Definitely, {topic} has enormous potential. I can't wait to learn more!",
    "Every conversation about {topic} leaves me with something new to reflect on. It's incredible!",
    "There's no limit to what we can learn from {topic}. I love this topic!",
]
"""English comments."""

FR_COMMENTS = [
    "J'aime tout ce qui concerne {topic}. Il y a toujours quelque chose nouveau à découvrir !",
    "{topic} est l'un de mes sujets favoris. Qu'en penses-tu ?",
    "Je n'aurais jamais pensé que {topic} puisse être aussi intéressant. Merci de partager !",
    "Je suis curieux d'en savoir plus sur {topic}. As-tu des recommandations ?",
    "{topic} arrive toujours à m'inspirer d'une certaine façon. C'est fascinant.",
    "C'est incroyable comme {topic} peut connecter tant de personnes. C'est génial !",
    "Je commence à m'intéresser vraiment à {topic}. Merci de me motiver à l'explorer.",
    "Sans aucun doute, {topic} est un sujet qui mérite plus d'attention. Bien dit !",
    "Chaque fois que je lis quelque chose sur {topic}, j'apprends quelque chose de nouveau. Merci !",
    "Savais-tu que {topic} avait un tel impact ? J'aimerais en savoir plus.",
    "Je n'arrive pas à croire à quel point j'ai apprécié {topic}. Je suis tellement enthousiaste !",
    "Parfois je me demande combien on peut apprendre de {topic}. C'est tellement intéressant !",
    "Chaque fois que je vois quelque chose sur {topic}, je me sens inspiré. Merci de partager !",
    "J'adore comment {topic} a toujours quelque chose de nouveau à offrir. C'est incroyable !",
    "C'est fascinant de voir comment {topic} évolue constamment. Tellement excitant !",
    "J'ai toujours voulu en apprendre plus sur {topic}. Cela me motive encore plus.",
    "{topic} est un sujet qui rassemble les gens. C'est ce que j'aime le plus !",
    "Chaque détail sur {topic} me fascine. C'est une vraie source d'inspiration !",
    "Merci de m'avoir montré une nouvelle perspective sur {topic}. Très intéressant !",
    "Lire sur {topic} améliore toujours ma journée. C'est incroyable ce qu'on peut apprendre !",
    "Je ne me lasse jamais de découvrir de nouvelles choses sur {topic}. Il y a toujours quelque chose d'intrigant !",
    "C'est impressionnant de voir comment {topic} peut impacter tant de vies. Inspirant !",
    "Grâce à {topic}, j'ai découvert une nouvelle passion. Comme c'est excitant !",
    "C'est impressionnant ce qu'on peut accomplir quand on parle de {topic}. Super sujet !",
    "Qui aurait pensé que {topic} pourrait être si motivant ? Merci de partager !",
    "Le monde de {topic} ne cesse jamais de m'étonner. Il y a toujours quelque chose de fascinant !",
    "Quand je pense à {topic}, je me sens tellement enthousiaste. Quel sujet passionnant !",
    "Définitivement, {topic} a un potentiel énorme. J'ai hâte d'en apprendre plus !",
    "Chaque conversation sur {topic} me laisse quelque chose de nouveau sur quoi réfléchir. C'est incroyable !",
    "Il n'y a pas de limite à ce qu'on peut apprendre de {topic}. J'adore ce sujet !",
]
"""French comments."""

DE_COMMENTS = [
    "Ich liebe alles, was mit {topic} zu tun hat. Es gibt immer etwas Neues zu entdecken!",
    "{topic} ist eines meiner Lieblingsthemen. Was denkst du?",
    "Ich hätte nie gedacht, dass {topic} so interessant sein könnte. Danke fürs Teilen!",
    "Ich bin neugierig, mehr über {topic} zu erfahren. Hast du Empfehlungen?",
    "{topic} inspiriert mich immer auf eine bestimmte Weise. Es ist faszinierend.",
    "Es ist erstaunlich, wie {topic} so viele Menschen verbinden kann. Es ist großartig!",
    "Ich beginne, mich sehr für {topic} zu interessieren. Danke für die Motivation, es zu erkunden.",
    "Ohne Zweifel ist {topic} ein Thema, das mehr Aufmerksamkeit verdient. Gut gesagt!",
    "Jedes Mal, wenn ich etwas über {topic} lese, lerne ich etwas Neues. Danke!",
    "Wusstest du, dass {topic} so großen Einfluss hat? Ich würde gerne mehr erfahren.",
    "Ich kann nicht glauben, wie sehr ich {topic} genossen habe. Ich bin aufgeregt!",
    "Manchmal frage ich mich, wie viel wir von {topic} lernen können. Es ist interessant!",
    "Jedes Mal, wenn ich etwas über {topic} sehe, fühle ich mich inspiriert. Danke fürs Teilen!",
    "Ich liebe es, wie {topic} immer etwas Neues zu bieten hat. Es ist unglaublich!",
    "Es ist faszinierend, wie {topic} ständig weiterentwickelt wird. So aufregend!",
    "Ich habe immer mehr über {topic} erfahren wollen. Das motiviert mich noch mehr.",
    "{topic} ist ein Thema, das Menschen zusammenbringt. Das ist, was ich am meisten liebe!",
    "Jedes Detail über {topic} fasziniert mich. Es ist eine Quelle der Inspiration!",
    "Danke für die neue Perspektive auf {topic}. Sehr interessant!",
    "Das Lesen über {topic} verbessert immer meinen Tag. Es ist unglaublich, was man lernen kann!",
    "Ich werde nie müde, neue Dinge über {topic} zu entdecken. Es gibt immer etwas Interessantes!",
    "Es ist erstaunlich, wie {topic} so viele Leben beeinflussen kann. Inspirierend!",
    "Dank {topic} habe ich eine neue Leidenschaft entdeckt. So aufregend!",
    "Es ist beeindruckend, was wir erreichen können, wenn wir über {topic} sprechen. Großartiges Thema!",
    "Wer hätte gedacht, dass {topic} so motivierend sein könnte? Danke fürs Teilen!",
    "Die Welt von {topic} überrascht mich immer wieder. Es gibt immer etwas Faszinierendes!",
    "Wenn ich an {topic} denke, fühle ich mich voller Enthusiasmus. Was für ein großartiges Thema!",
    "Definitiv hat {topic} enormes Potenzial. Ich kann nicht erwarten, mehr zu lernen!",
    "Jedes Gespräch über {topic} lässt mich mit etwas Neuem nachdenken. Es ist unglaublich!",
    "Es gibt keine Grenzen dafür, was wir von {topic} lernen können. Ich liebe dieses Thema!",
]
"""German comments."""

COMMENTS = {
    'es': ES_COMMENTS,
    'en': EN_COMMENTS,
    'fr': FR_COMMENTS,
    'de': DE_COMMENTS,
}
"""Comments by language."""
