"""Details."""

ES_DETAILS = [
    "con amigos cercanos.",
    "mientras tomaba un café.",
    "y descubrí algo sorprendente.",
    "que me dejó pensando todo el día.",
    "y realmente fue inspirador.",
    "durante una tarde tranquila.",
    "y sentí una gran conexión.",
    "que cambió mi forma de ver las cosas.",
    "y me llenó de energía positiva.",
    "mientras disfrutaba del atardecer.",
    "que trajo mucha felicidad a mi día.",
    "y fue una experiencia única.",
    "que me motivó a seguir adelante.",
    "y me hizo reflexionar profundamente.",
    "durante una conversación interesante.",
    "y sentí una paz increíble.",
    "que me recordó lo importante que es vivir el momento.",
    "y aprendí algo valioso.",
    "que me conectó con mi pasión.",
    "y fue un regalo inesperado.",
    "en un día lleno de retos.",
    "y me dejó una gran sonrisa.",
    "que iluminó mi día.",
    "mientras exploraba un nuevo lugar.",
    "que me inspiró a ser mejor.",
    "y me hizo sentir muy agradecido.",
    "en una experiencia inolvidable.",
    "que fue un verdadero placer.",
    "y abrió nuevas posibilidades.",
    "y me dejó con ganas de seguir adelante.",
]
"""Spanish details."""

EN_DETAILS = [
    "with close friends.",
    "while having a coffee.",
    "and discovered something surprising.",
    "that kept me thinking all day.",
    "and it was truly inspiring.",
    "during a quiet afternoon.",
    "and felt a great connection.",
    "that changed the way I see things.",
    "and filled me with positive energy.",
    "while enjoying the sunset.",
    "that brought a lot of happiness to my day.",
    "and it was a unique experience.",
    "that motivated me to keep going.",
    "and made me reflect deeply.",
    "during an interesting conversation.",
    "and felt an incredible peace.",
    "that reminded me how important it is to live in the moment.",
    "and learned something valuable.",
    "that connected me with my passion.",
    "and it was an unexpected gift.",
    "on a day full of challenges.",
    "and left me with a big smile.",
    "that brightened my day.",
    "while exploring a new place.",
    "that inspired me to be better.",
    "and made me feel very grateful.",
    "in an unforgettable experience.",
    "that was a true pleasure.",
    "and opened new possibilities.",
    "and made me want to keep going.",
]
"""English details."""

FR_DETAILS = [
    "avec des amis proches.",
    "en prenant un café.",
    "et j'ai découvert quelque chose de surprenant.",
    "qui m'a fait réfléchir toute la journée.",
    "et c'était vraiment inspirant.",
    "pendant une après-midi tranquille.",
    "et j'ai ressenti une grande connexion.",
    "qui a changé ma façon de voir les choses.",
    "et m'a rempli d'énergie positive.",
    "en profitant du coucher du soleil.",
    "qui a apporté beaucoup de joie à ma journée.",
    "et c'était une expérience unique.",
    "qui m'a motivé à continuer.",
    "et m'a fait réfléchir profondément.",
    "pendant une conversation intéressante.",
    "et j'ai ressenti une paix incroyable.",
    "qui m'a rappelé l'importance de vivre l'instant présent.",
    "et j'ai appris quelque chose de précieux.",
    "qui m'a connecté à ma passion.",
    "et c'était un cadeau inattendu.",
    "lors d'une journée pleine de défis.",
    "et m'a laissé avec un grand sourire.",
    "qui a illuminé ma journée.",
    "en explorant un nouvel endroit.",
    "qui m'a inspiré à devenir meilleur.",
    "et m'a fait me sentir très reconnaissant.",
    "dans une expérience inoubliable.",
    "qui était un véritable plaisir.",
    "et a ouvert de nouvelles possibilités.",
    "et m'a donné envie de continuer.",
]
"""French details."""

DE_DETAILS = [
    "mit engen Freunden.",
    "beim Kaffeetrinken.",
    "und entdeckte etwas Überraschendes.",
    "das mich den ganzen Tag beschäftigte.",
    "und es war wirklich inspirierend.",
    "an einem ruhigen Nachmittag.",
    "und spürte eine starke Verbindung.",
    "das meine Sichtweise veränderte.",
    "und erfüllte mich mit positiver Energie.",
    "während ich den Sonnenuntergang genoss.",
    "das meinem Tag viel Freude brachte.",
    "und es war eine einzigartige Erfahrung.",
    "das mich motivierte weiterzumachen.",
    "und brachte mich zum tiefen Nachdenken.",
    "während eines interessanten Gesprächs.",
    "und fühlte einen unglaublichen Frieden.",
    "das mich daran erinnerte, wie wichtig es ist, im Moment zu leben.",
    "und lernte etwas Wertvolles.",
    "das mich mit meiner Leidenschaft verband.",
    "und es war ein unerwartetes Geschenk.",
    "an einem Tag voller Herausforderungen.",
    "und hinterließ ein großes Lächeln.",
    "das meinen Tag erhellte.",
    "während ich einen neuen Ort erkundete.",
    "das mich inspirierte, besser zu werden.",
    "und machte mich sehr dankbar.",
    "in einer unvergesslichen Erfahrung.",
    "das ein wahres Vergnügen war.",
    "und eröffnete neue Möglichkeiten.",
    "und gab mir Lust weiterzumachen.",
]
"""German details."""

DETAILS = {
    'es': ES_DETAILS,
    'en': EN_DETAILS,
    'fr': FR_DETAILS,
    'de': DE_DETAILS,
}
"""Details by language."""
