"""Mail domains."""

MAIL_DOMAINS = [
    'yopmail.com',
    'tempmail.com',
    '10minutemail.com',
    'guerrillamail.com',
    'mailinator.com',
    'throwawaymail.com',
    'maildrop.cc',
    'getnada.com',
    'temp-mail.org',
    'moakt.com',
    'mytemp.email',
    'tempmailaddress.com',
    'fakemailgenerator.com',
    'trashmail.com',
    'mailcatch.com',
    'tempail.com',
    'emailondeck.com',
    'instant-email.org',
    'spamgourmet.com',
    'mailnesia.com',
    'dispostable.com',
    'mintemail.com',
    'spamfree24.org',
    'tempemail.co',
    'tempmailo.com',
    'easytrashmail.com',
    'temp-mail.io',
    'mail-temporaire.fr',
    'tempmail.net',
    'tempmail.de',
]
"""Mail domains."""
