"""Text starts."""

ES_STARTS = [
    "Hoy estuve pensando en lo increíble que es",
    "No puedo creer lo mucho que disfruté de",
    "Quiero compartir una experiencia sobre",
    "Algo que siempre me motiva es",
    "¿Alguna vez has probado",
    "A veces me pregunto cuánto podemos aprender de",
    "Es sorprendente lo que descubrí sobre",
    "Nunca imaginé cuánto podría disfrutar de",
    "La vida siempre es mejor cuando incluyes",
    "Un momento especial para mí fue con",
    "Últimamente he estado muy interesado en",
    "Me siento inspirado por",
    "Una experiencia inolvidable fue cuando descubrí",
    "Siempre he tenido curiosidad por",
    "¿Quién más disfruta de",
    "Hoy quiero hablar sobre",
    "He aprendido mucho gracias a",
    "Una gran lección de la vida incluye",
    "Nada se compara con la emoción de explorar",
    "A veces lo más simple, como",
    "Cada día es una nueva oportunidad para disfrutar de",
    "El poder de",
    "No hay límites para lo que podemos lograr con",
    "Algo mágico sucede cuando piensas en",
    "¿Qué opinas de",
    "Quiero tomarme un momento para reflexionar sobre",
    "La alegría de vivir está en disfrutar de",
    "Todo cambia cuando experimentas",
    "Hoy me sentí conectado con",
    "Me siento motivado por",
    "La belleza de",
    "El arte de",
]
"""Spanish text starts."""

EN_STARTS = [
    "Today I was thinking about how amazing it is",
    "I can't believe how much I enjoyed",
    "I want to share an experience about",
    "Something that always motivates me is",
    "Have you ever tried",
    "Sometimes I wonder how much we can learn from",
    "It's surprising what I discovered about",
    "I never imagined how much I could enjoy",
    "Life is always better when you include",
    "A special moment for me was with",
    "Lately, I've been very interested in",
    "I feel inspired by",
    "An unforgettable experience was when I discovered",
    "I've always been curious about",
    "Who else enjoys",
    "Today I want to talk about",
    "I've learned a lot thanks to",
    "A great life lesson includes",
    "Nothing compares to the thrill of exploring",
    "Sometimes the simplest things, like",
    "Every day is a new opportunity to enjoy",
    "The power of",
    "There are no limits to what we can achieve with",
    "Something magical happens when you think about",
    "What do you think about",
    "I want to take a moment to reflect on",
    "The joy of living is in enjoying",
    "Everything changes when you experience",
    "Today I felt connected with",
    "I feel motivated by",
    "The beauty of",
    "The art of",
]
"""English text starts."""

FR_STARTS = [
    "Aujourd'hui, j'ai pensé à quel point c'est fantastique",
    "Je ne peux pas croire à quel point j'ai apprécié",
    "Je veux partager une expérience sur",
    "Une chose qui me motive toujours est",
    "Avez-vous déjà essayé",
    "Parfois, je me demande combien nous pouvons apprendre de",
    "C'est surprenant ce que j'ai découvert sur",
    "Je n'imaginais jamais à quel point je pouvais apprécier",
    "La vie est toujours meilleure quand vous incluez",
    "Un moment spécial pour moi était avec",
    "Récemment, je me suis beaucoup intéressé à",
    "Je me sens inspiré par",
    "Une expérience inoubliable fut quand j'ai découvert",
    "J'ai toujours été curieux de",
    "Qui d'autre aime",
    "Aujourd'hui, je veux parler de",
    "J'ai beaucoup appris grâce à",
    "Une grande leçon de vie comprend",
    "Rien ne se compare au plaisir d'explorer",
    "Parfois, les choses les plus simples, comme",
    "Chaque jour est une nouvelle opportunité d'apprécier",
    "Le pouvoir de",
    "Il n'y a pas de limites à ce que nous pouvons accomplir avec",
    "Quelque chose de magique se produit quand on pense à",
    "Que pensez-vous de",
    "Je veux prendre un moment pour réfléchir à",
    "La joie de vivre est dans l'appréciation de",
    "Tout change quand on expérimente",
    "Aujourd'hui, je me sens connecté avec",
    "Je me sens motivé par",
    "La beauté de",
    "L'art de",
]
"""French text starts."""

DE_STARTS = [
    "Heute habe ich darüber nachgedacht, wie fantastisch es ist",
    "Ich kann nicht glauben, wie sehr ich es genossen habe",
    "Ich möchte eine Erfahrung teilen über",
    "Etwas, das mich immer motiviert, ist",
    "Hast du jemals versucht",
    "Manchmal frage ich mich, wie viel wir lernen können von",
    "Es ist überraschend, was ich entdeckt habe über",
    "Ich hätte nie gedacht, wie sehr ich es genießen würde",
    "Das Leben ist immer besser, wenn man einbezieht",
    "Ein besonderer Moment für mich war mit",
    "In letzter Zeit habe ich mich sehr interessiert für",
    "Ich fühle mich inspiriert durch",
    "Eine unvergessliche Erfahrung war, als ich entdeckte",
    "Ich war schon immer neugierig auf",
    "Wer sonst genießt",
    "Heute möchte ich sprechen über",
    "Ich habe viel gelernt durch",
    "Eine wichtige Lebenslektion beinhaltet",
    "Nichts kommt der Freude gleich",
    "Manchmal sind es die einfachen Dinge, wie",
    "Jeder Tag ist eine neue Chance zu genießen",
    "Die Kraft von",
    "Es gibt keine Grenzen für das, was wir erreichen können mit",
    "Etwas Magisches passiert, wenn man denkt an",
    "Was denken Sie über",
    "Ich möchte einen Moment nehmen, um nachzudenken über",
    "Die Freude am Leben liegt im Genießen von",
    "Alles verändert sich, wenn man erlebt",
    "Heute fühle ich mich verbunden mit",
    "Ich fühle mich motiviert durch",
    "Die Schönheit von",
    "Die Kunst des",
]
"""German text starts."""

STARTS = {
    'es': ES_STARTS,
    'en': EN_STARTS,
    'fr': FR_STARTS,
    'de': DE_STARTS,
}
"""Text starts by language."""
