"""Topics."""

ES_TOPICS = [
    "la tecnología",
    "los viajes",
    "la cocina",
    "los deportes",
    "la música",
    "la ciencia",
    "la moda",
    "el arte",
    "los autos",
    "la literatura",
    "la historia",
    "el cine",
    "la fotografía",
    "los videojuegos",
    "la astronomía",
    "la salud",
    "la educación",
    "el emprendimiento",
    "la naturaleza",
    "los animales",
    "el teatro",
    "la arquitectura",
    "la jardinería",
    "la psicología",
    "la meditación",
    "la filosofía",
    "la política",
    "la economía",
    "la tecnología espacial",
    "la sostenibilidad",
    "la inteligencia artificial",
]
"""Spanish topics."""

EN_TOPICS = [
    "the technology",
    "the travel",
    "the cooking",
    "the sports",
    "the music",
    "the science",
    "the fashion",
    "the art",
    "the cars",
    "the literature",
    "the history",
    "the cinema",
    "the photography",
    "the video games",
    "the astronomy",
    "the health",
    "the education",
    "the entrepreneurship",
    "the nature",
    "the animals",
    "the theater",
    "the architecture",
    "the gardening",
    "the psychology",
    "the meditation",
    "the philosophy",
    "the politics",
    "the economy",
    "the space technology",
    "the sustainability",
    "the artificial intelligence",
]
"""English topics."""

FR_TOPICS = [
    "la technologie",
    "les voyages",
    "la cuisine",
    "les sports",
    "la musique",
    "la science",
    "la mode",
    "l'art",
    "les voitures",
    "la littérature",
    "l'histoire",
    "le cinéma",
    "la photographie",
    "les jeux vidéo",
    "l'astronomie",
    "la santé",
    "l'éducation",
    "l'entrepreneuriat",
    "la nature",
    "les animaux",
    "le théâtre",
    "l'architecture",
    "le jardinage",
    "la psychologie",
    "la méditation",
    "la philosophie",
    "la politique",
    "l'économie",
    "la technologie spatiale",
    "le développement durable",
    "l'intelligence artificielle",
]
"""French topics."""

DE_TOPICS = [
    "die Technologie",
    "das Reisen",
    "das Kochen",
    "der Sport",
    "die Musik",
    "die Wissenschaft",
    "die Mode",
    "die Kunst",
    "die Autos",
    "die Literatur",
    "die Geschichte",
    "das Kino",
    "die Fotografie",
    "die Videospiele",
    "die Astronomie",
    "die Gesundheit",
    "die Bildung",
    "das Unternehmertum",
    "die Natur",
    "die Tiere",
    "das Theater",
    "die Architektur",
    "die Gartenarbeit",
    "die Psychologie",
    "die Meditation",
    "die Philosophie",
    "die Politik",
    "die Wirtschaft",
    "die Raumfahrttechnologie",
    "die Nachhaltigkeit",
    "die Künstliche Intelligenz",
]
"""German topics."""

TOPICS = {
    'es': ES_TOPICS,
    'en': EN_TOPICS,
    'fr': FR_TOPICS,
    'de': DE_TOPICS,
}
"""Topics by language."""
