
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-11T11:05:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "26fed9fd3dc9101fa08d947da4153d60449f316c",
 "version": "2.56.3b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
