
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-11T15:41:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "66c0a60beeb5c44b7e2f3fde117b75f5a1711f99",
 "version": "0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
