# coding: utf-8

"""
    OneRoster OpenAPI (JSON) Definition

    The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: platform@strongmind.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SingleAcademicSessionType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'academic_session': 'AcademicSessionType'
    }

    attribute_map = {
        'academic_session': 'academicSession'
    }

    def __init__(self, academic_session=None):  # noqa: E501
        """SingleAcademicSessionType - a model defined in Swagger"""  # noqa: E501
        self._academic_session = None
        self.discriminator = None
        self.academic_session = academic_session

    @property
    def academic_session(self):
        """Gets the academic_session of this SingleAcademicSessionType.  # noqa: E501


        :return: The academic_session of this SingleAcademicSessionType.  # noqa: E501
        :rtype: AcademicSessionType
        """
        return self._academic_session

    @academic_session.setter
    def academic_session(self, academic_session):
        """Sets the academic_session of this SingleAcademicSessionType.


        :param academic_session: The academic_session of this SingleAcademicSessionType.  # noqa: E501
        :type: AcademicSessionType
        """
        if academic_session is None:
            raise ValueError("Invalid value for `academic_session`, must not be `None`")  # noqa: E501

        self._academic_session = academic_session

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SingleAcademicSessionType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SingleAcademicSessionType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
