VERSION_NUMBER = "1.0.0"

VAL2PY_MAPPINGS = {
    "bait": "try",
    "trade": "except",
    r"post\s+plant": "finally",
    "save": "break",
    "eco": "continue",
    r"clutch\s+or\s+kick": "if",
    "retake": "elif",
    "defuse": "else",
    r"run\s+it\s+back": "return",  # phoenix ult
    r"agent\s+kit": "class",
    r"rebaib\s+me": "self",  # reference to revive me jett
    "headshot": "*",
    "wallbang": "-",
    "healing": "+",
    r"double\s+peek": "and",
    "rotate": "or",
    "whiff": "not",
    "there": "in",
    "fakeout": "as",  # yoru clone
    r"hold\s+position": "while",
    "spam": "for",
    "chat": "print",
    "loadout": "def",
    r"rank\s+reset": "del",
    "afk": "None",
    r"brain\s+lag": "await",
    r"multi\s+task": "async",
    r"game\s+dev": "exec",
    r"map\s+control": "global",
    "buy": "import",
    "lurker": "nonlocal",
    "standby": "pass",
    "ban": "raise",
    r"neural\s+theft": "assert",
    "victory": "True",
    "defeat": "False",
    "shop": "from",
    "shiftwalk": "lambda",
    "stack": "with",
    "tag": "is",
    "remake": "yield",
    "surrender": "yield from",
    "rush": "open",
    "camp": "close",
}
