# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
from .update_reasoning_message_reasoning import UpdateReasoningMessageReasoning
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class UpdateReasoningMessage(UncheckedBaseModel):
    reasoning: UpdateReasoningMessageReasoning
    message_type: typing.Literal["reasoning_message"] = "reasoning_message"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
