# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: informaticsmatters/protobuf/accountserver/merchant_storage_charge_message.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nOinformaticsmatters/protobuf/accountserver/merchant_storage_charge_message.proto\x12)informaticsmatters.protobuf.accountserver\"\xce\x02\n\x1cMerchantStorageChargeMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x15\n\rmerchant_kind\x18\x02 \x01(\t\x12\x15\n\rmerchant_name\x18\x03 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x04 \x01(\r\x12L\n\x06reason\x18\x05 \x01(\x0e\x32<.informaticsmatters.protobuf.accountserver.StorageReasonEnum\x12\x11\n\tauth_code\x18\x06 \x01(\r\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\r\n\x05\x62ytes\x18\x08 \x01(\t\x12\x0c\n\x04user\x18\x10 \x01(\t\x12\x0f\n\x07product\x18\x11 \x01(\t\x12\x0c\n\x04unit\x18\x12 \x01(\t\x12\x14\n\x0corganisation\x18\x13 \x01(\t\x12\x17\n\x0f\x61\x64\x64itional_data\x18\x1e \x01(\t*z\n\x11StorageReasonEnum\x12#\n\x1fSTORAGE_REASON_ENUM_UNSPECIFIED\x10\x00\x12\x1f\n\x1bSTORAGE_REASON_ENUM_DATASET\x10\x01\x12\x1f\n\x1bSTORAGE_REASON_ENUM_PROJECT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'informaticsmatters.protobuf.accountserver.merchant_storage_charge_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STORAGEREASONENUM']._serialized_start=463
  _globals['_STORAGEREASONENUM']._serialized_end=585
  _globals['_MERCHANTSTORAGECHARGEMESSAGE']._serialized_start=127
  _globals['_MERCHANTSTORAGECHARGEMESSAGE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
