class TooManyMatchingGroupsError(Exception): ...
class NoMatchingGroupError(Exception): ...
class UnableToFindApplicationError(Exception): ...
class UnableToFindUserError(Exception): ...
class UnableToFindManagerError(Exception): ...