"""
    EMIL PartnerPortal

    The EMIL PartnerPortal API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.partner-portal
from eis.partner-portal.model.partner_role_class import PartnerRoleClass


class TestPartnerRoleClass(unittest.TestCase):
    """PartnerRoleClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartnerRoleClass(self):
        """Test PartnerRoleClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PartnerRoleClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
