# coding: utf-8

"""
    OneRoster OpenAPI (JSON) Definition

    The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: lmattson@imsglobal.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import oneroster_client
from oneroster_client.models.line_items_type import LineItemsType  # noqa: E501
from oneroster_client.rest import ApiException


class TestLineItemsType(unittest.TestCase):
    """LineItemsType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLineItemsType(self):
        """Test LineItemsType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = oneroster_client.models.line_items_type.LineItemsType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
