# coding: utf-8

"""
    OneRoster OpenAPI (JSON) Definition

    The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: lmattson@imsglobal.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import oneroster_client
from oneroster_client.api.demographics_management_api import DemographicsManagementApi  # noqa: E501
from oneroster_client.rest import ApiException


class TestDemographicsManagementApi(unittest.TestCase):
    """DemographicsManagementApi unit test stubs"""

    def setUp(self):
        self.api = DemographicsManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_demographic(self):
        """Test case for get_demographic

        The REST read request message for the getDemographic() API call.  # noqa: E501
        """
        pass

    def test_get_demographics(self):
        """Test case for get_demographics

        The REST read request message for the getDemographics() API call.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
