# coding: utf-8

"""
    OneRoster OpenAPI (JSON) Definition

    The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: lmattson@imsglobal.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import oneroster_client
from oneroster_client.api.resources_management_api import ResourcesManagementApi  # noqa: E501
from oneroster_client.rest import ApiException


class TestResourcesManagementApi(unittest.TestCase):
    """ResourcesManagementApi unit test stubs"""

    def setUp(self):
        self.api = ResourcesManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_resource(self):
        """Test case for get_resource

        The REST read request message for the getResource() API call.  # noqa: E501
        """
        pass

    def test_get_resources(self):
        """Test case for get_resources

        The REST read request message for the getResources() API call.  # noqa: E501
        """
        pass

    def test_get_resources_for_class(self):
        """Test case for get_resources_for_class

        The REST read request message for the getResourcesForClass() API call.  # noqa: E501
        """
        pass

    def test_get_resources_for_course(self):
        """Test case for get_resources_for_course

        The REST read request message for the getResourcesForCourse() API call.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
