

class AccountTypeLabels:
    HANDSHAKE = 'HANDSHAKE'
    GDOC_CONTEXT_LINK = 'google_doc_context_link'
    CONTEXT_DOC_LINK = 'context_link'
    INITIATION_RITE = 'INITIATION_RITE'
    WALLET_FUNDING = 'discord_wallet_funding'
    INITIATION_REWARD = 'INITIATION_REWARD'
    SWEEP_ADDRESS = 'SWEEP WALLET'
    BLACKLIST = 'BLACKLIST'

class TaskTypeLabels:
    REQUEST = 'REQUEST_POST_FIAT'
    PROPOSED = 'PROPOSED PF'
    ACCEPTANCE = 'ACCEPTANCE REASON'
    REFUSAL = 'REFUSAL REASON'
    COMPLETION = 'COMPLETION JUSTIFICATION'
    CHALLENGE = 'VERIFICATION PROMPT'
    RESPONSE = 'VERIFICATION RESPONSE'
    REWARD = 'REWARD RESPONSE'
