
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-12T10:04:52+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "6f0fb30e8ed98b8b5df9c0d222e98713214f84bd",
 "version": "0.11.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
