
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-13T11:20:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "71d779964e5756b89c6237e1550112d9c8a77498",
 "version": "0.5.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
