
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-14T11:32:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a05be62068c5b2ef243b7a101310eed67e2dacf8",
 "version": "2.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
