
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-14T16:48:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebf8ea25cc4a9fa18773b5fed644293922bff5cb",
 "version": "2.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
