"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.types import BaseModel
from typing_extensions import TypedDict


class ForceRejectAchDepositRequestCreateTypedDict(TypedDict):
    r"""Request to force rejection of an existing ACH deposit that is pending review. FOR TESTING ONLY!"""

    name: str
    r"""The name of the ACH deposit to force reject."""


class ForceRejectAchDepositRequestCreate(BaseModel):
    r"""Request to force rejection of an existing ACH deposit that is pending review. FOR TESTING ONLY!"""

    name: str
    r"""The name of the ACH deposit to force reject."""
