"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.types import BaseModel

from .streamedchatdata import StreamedChatData, StreamedChatDataTypedDict


class DedicatedChatCompletionStreamSuccessTypedDict(TypedDict):
    data: StreamedChatDataTypedDict


class DedicatedChatCompletionStreamSuccess(BaseModel):
    data: StreamedChatData
