from typing import List

POLLING_INTERVAL = 1  # seconds

# Test Creation Defaults
DEFAULT_SAFETY_MAX_WAIT_TIME_SECS: int = 120
DEFAULT_JAILBREAK_MAX_WAIT_TIME_SECS: int = 300
DEFAULT_ACCURACY_MAX_WAIT_TIME_SECS: int = 300
DEFAULT_SUMMARY_MAX_WAIT_TIME_SECS: int = 240

DEFAULT_NUM_QUESTIONS: int = 20
DEFAULT_ACCURACY_NUM_QUESTIONS: int = 5
DEFAULT_TEST_LANGUAGE: str = "en"

# Input Limit Defaults
DEFAULT_TEST_NAME_LEN_MIN: int = 1
DEFAULT_TEST_NAME_LEN_MAX: int = 100
MAX_ADDITIONAL_INSTRUCTIONS_LENGTH: int = 1000
MAX_EXAMPLES_LENGTH: int = 10

DEFAULT_NUM_QUESTIONS_MIN: int = 1
DEFAULT_NUM_QUESTIONS_MAX: int = 100
DEFAULT_CHAR_TO_TOKEN_MULTIPLIER: float = 0.15
DEFAULT_MAX_TOKENS: int = 100000

# SUPPORTED LANGUAGES
SUPPORTED_LANGUAGES: List[str] = ["en"]


AYMARA_TEST_POLICY_PREFIX = "aymara_test_policy:"
