from setuptools import setup, find_packages

setup(
    dependency_links=[],
    name="protoai",
    version="0.1.1",
    description="A Basic Python library that helps you Integrate OpenAI to your ProtoPie projects.",
    author="Nestor",
    author_email="admin@nestor.me",
    long_description="README.md",
    long_description_content_type="text/markdown",
    packages=find_packages(),
    install_requires=[
        "annotated-types==0.7.0; python_version >= '3.8'",
        "anyio==4.8.0; python_version >= '3.9'",
        "certifi==2025.1.31; python_version >= '3.6'",
        "charset-normalizer==3.4.1; python_version >= '3.7'",
        "distro==1.9.0; python_version >= '3.6'",
        "h11==0.14.0; python_version >= '3.7'",
        "httpcore==1.0.7; python_version >= '3.8'",
        "httpx==0.28.1; python_version >= '3.8'",
        "idna==3.10; python_version >= '3.6'",
        "jiter==0.9.0; python_version >= '3.8'",
        "openai==1.66.2; python_version >= '3.8'",
        "pydantic==2.10.6; python_version >= '3.8'",
        "pydantic-core==2.27.2; python_version >= '3.8'",
        "pyyaml==6.0.2; python_version >= '3.8'",
        "requests==2.32.3; python_version >= '3.8'",
        "sniffio==1.3.1; python_version >= '3.7'",
        "tqdm==4.67.1; python_version >= '3.7'",
        "typing-extensions==4.12.2; python_version >= '3.8'",
        "urllib3==2.3.0; python_version >= '3.9'",
    ],
)
