__name__ ='base_scraper'
__version__ = '1.0.2'
__date__ = '2025-03-11'
__author__ = 'ktxo'
__author_email__ = 'ktxotec@gmail.com'
__url__ = 'https://github.com/ktxo/main-scraper'
__description__ = 'Wrapper class for Selenium'
__description_message__ = 'Wrapper class for Selenium (base for scrapers, rpa software)'