
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-12T01:02:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c03cbfe661994e80ff86d1513880e296ef366092",
 "version": "v0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
