# Generated by Django 3.2.13 on 2022-04-23 23:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='zb_youtube_pluginconfig', serialize=False, to='cms.cmsplugin')),
                ('channel_id', models.CharField(blank=True, default='', max_length=100)),
                ('max_results', models.IntegerField(default=4)),
                ('video_order', models.CharField(choices=[('date', 'Date'), ('rating', 'Rating'), ('relevance', 'Relevance'), ('title', 'Title'), ('videoCount', 'Video Count'), ('viewCount', 'View Count')], default='date', max_length=10)),
                ('video_template', models.CharField(default='zb_youtube.html', max_length=50)),
                ('video_width', models.IntegerField(default=560)),
                ('video_height', models.IntegerField(default=315)),
                ('video_columns', models.IntegerField(default=2)),
                ('thumbnail_definition', models.CharField(choices=[('default', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('refresh_time', models.IntegerField(default=360, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(1440)])),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
