# Generated by Django 3.2.13 on 2022-05-17 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_zb_youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginconfig',
            name='channel_id',
            field=models.CharField(blank=True, default='', help_text='Youtube channel id to view', max_length=100, verbose_name='Channel Id'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_zb_youtube_pluginconfig', serialize=False, to='cms.cmsplugin'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='max_results',
            field=models.IntegerField(default=4, help_text='Max number of videos to be fetched from Youtube', verbose_name='Max results'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='refresh_time',
            field=models.IntegerField(default=360, help_text='Time to be used to refresh the video list from youtube', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(1440)], verbose_name='Refresh time'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='thumbnail_definition',
            field=models.CharField(choices=[('default', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Definition of thumbnail to be used', max_length=10, verbose_name='Thumbnail definition'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='video_columns',
            field=models.IntegerField(default=2, help_text='Number of columns in which the videos will be displayed', verbose_name='Display columns'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='video_height',
            field=models.IntegerField(default=315, help_text='Height of video in pixels', verbose_name='Video height'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='video_order',
            field=models.CharField(choices=[('date', 'Date'), ('rating', 'Rating'), ('relevance', 'Relevance'), ('title', 'Title'), ('videoCount', 'Video Count'), ('viewCount', 'View Count')], default='date', help_text='Order in which videos are displayed', max_length=10, verbose_name='Video order'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='video_template',
            field=models.CharField(default='zb_youtube.html', help_text='Template to be used to display the videos', max_length=50, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='video_width',
            field=models.IntegerField(default=560, help_text='Width of video in pixels', verbose_name='Video width'),
        ),
    ]
