export let GRAPHFONTSIZE: number = 13.5;
export const COMMITHEIGHT: number = 48;
export const LINESPACING: number = 12;
export const COMMITRADIUS: number = 5;
export const MESSAGEMARGINX: number = 20;
export const MESSAGEMARGINY: number = 0;
export const CURRENTCOMMITRADUIS: number = 10;
export const DATEHEADERHEIGHT: number = 30;
export const MARGINMESSAGE:number = 5;
export const COLORSPAN = ["#3398fd", "#8d5deb", "#e94698", "#fd8700", "#d75ab6"]
