"""Hashtags."""

ES_HASHTAGS = [
    '#Increíble',
    '#Inspirador',
    '#Motivación',
    '#VidaDiaria',
    '#Aprendizaje',
    '#Éxito',
    '#Crecimiento',
    '#DesarrolloPersonal',
    '#Reflexión',
    '#Metas',
    '#Desarrollo',
    '#Habilidades',
    '#Consejos',
    '#Experiencia',
    '#Tecnología',
    '#Negocios',
    '#Salud',
    '#Viajes',
    '#Cultura',
    '#Innovación',
    '#Emprendimiento',
    '#Liderazgo',
    '#Comunicación',
    '#Colaboración',
    '#Creatividad',
    '#Productividad',
    '#Gestión',
    '#Estrategia',
    '#Alegría',
    '#Gratitud',
    '#Paciencia',
    '#Resiliencia',
    '#MentalidadPositiva',
    '#AprendizajeContinuo',
    '#DesarrolloProfesional',
    '#Conocimiento',
    '#Educación',
]
"""Spanish hashtags."""

EN_HASHTAGS = [
    '#Amazing',
    '#Inspiring',
    '#Motivation',
    '#DailyLife',
    '#Learning',
    '#Success',
    '#Growth',
    '#PersonalGrowth',
    '#Reflection',
    '#Goals',
    '#Development',
    '#Skills',
    '#Tips',
    '#Experience',
    '#Technology',
    '#Business',
    '#Health',
    '#Travel',
    '#Culture',
    '#Innovation',
    '#Entrepreneurship',
    '#Leadership',
    '#Communication',
    '#Collaboration',
    '#Creativity',
    '#Productivity',
    '#Management',
    '#Strategy',
    '#Joy',
    '#Gratitude',
    '#Patience',
    '#Resilience',
    '#PositiveMindset',
    '#ContinuousLearning',
    '#ProfessionalDevelopment',
    '#Knowledge',
    '#Education',
]
"""English hashtags."""

FR_HASHTAGS = [
    '#Incroyable',
    '#Inspirant',
    '#Motivation',
    '#VieQuotidienne',
    '#Apprentissage',
    '#Réussite',
    '#Croissance',
    '#DéveloppementPersonnel',
    '#Réflexion',
    '#Objectifs',
    '#Développement',
    '#Compétences',
    '#Conseils',
    '#Expérience',
    '#Technologie',
    '#Entreprise',
    '#Santé',
    '#Voyage',
    '#Culture',
    '#Innovation',
    '#Entrepreneuriat',
    '#Leadership',
    '#Communication',
    '#Collaboration',
    '#Créativité',
    '#Productivité',
    '#Gestion',
    '#Stratégie',
    '#Joie',
    '#Gratitude',
    '#Patience',
    '#Résilience',
    '#EspritPositif',
    '#FormationContinue',
    '#DéveloppementPro',
    '#Savoir',
    '#Éducation',
]
"""French hashtags."""

DE_HASHTAGS = [
    '#Erstaunlich',
    '#Inspirierend',
    '#Motivation',
    '#Alltag',
    '#Lernen',
    '#Erfolg',
    '#Wachstum',
    '#Persönlichkeitsentwicklung',
    '#Reflexion',
    '#Ziele',
    '#Entwicklung',
    '#Fähigkeiten',
    '#Tipps',
    '#Erfahrung',
    '#Technologie',
    '#Wirtschaft',
    '#Gesundheit',
    '#Reisen',
    '#Kultur',
    '#Innovation',
    '#Unternehmertum',
    '#Führung',
    '#Kommunikation',
    '#Zusammenarbeit',
    '#Kreativität',
    '#Produktivität',
    '#Management',
    '#Strategie',
    '#Freude',
    '#Dankbarkeit',
    '#Geduld',
    '#Resilienz',
    '#PositivesDenken',
    '#Weiterbildung',
    '#BeruflicheEntwicklung',
    '#Wissen',
    '#Bildung',
]
"""German hashtags."""

HASHTAGS = {
    'es': ES_HASHTAGS,
    'en': EN_HASHTAGS,
    'fr': FR_HASHTAGS,
    'de': DE_HASHTAGS,
}
"""Hashtags by language."""
