DROP PROCEDURE IF EXISTS REPLACE_STR;
-- DROP FUNCTION IF EXISTS SPLIT_STR;
-- DROP FUNCTION IF EXISTS COUNT_STR_SEPARATOR;
DROP PROCEDURE IF EXISTS ReplaceValuesByJson;
DROP PROCEDURE IF EXISTS REPLACE_STR_BY_MAPPING;