# Generated by Django 5.1.7 on 2025-03-13 21:49

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_photo_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpicturetranslation',
            name='caption',
            field=djangocms_text.fields.HTMLField(
                blank=True, verbose_name='caption'
            ),
        ),
    ]
