# coding: utf-8

"""
    Wandelbots Nova API

    Interact with robots in an easy and intuitive way. 

    The version of the OpenAPI document: 2.0.0 beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IODirection(str, Enum):
    """
    Identifies the I/O type. Possible responses \"input\" or \"output\".
    """

    """
    allowed enum values
    """
    IO_TYPE_INPUT = 'IO_TYPE_INPUT'
    IO_TYPE_OUTPUT = 'IO_TYPE_OUTPUT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IODirection from a JSON string"""
        return cls(json.loads(json_str))


