"""
Django settings for tracker project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

print(os.path.join(BASE_DIR, 'templates'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3o_@&oc0!@s%&x$ldq8g1^a95d62ws+b6iijhore42uk90r1s0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['1a03163033cb41b081e03a1cfe09181a.vfs.cloud9.us-east-1.amazonaws.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'time_tracker', #register new application
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware', #메세지 출력
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_REDIRECT_URL = 'dashboard'  # 로그인 후 리다이렉트할 URL
LOGIN_URL = '/login/' # 로그인 페이지 리디렉션 설정
AUTH_USER_MODEL = 'time_tracker.CustomUser'

ROOT_URLCONF = 'tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # templates 디렉토리 경로
        'APP_DIRS': True,  # 앱 내 templates 폴더 확인
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# AWS S3 설정 (여기에 본인의 값을 입력)
#AWS_ACCESS_KEY_ID = "ASIAUBQBANIFNBGR45SW"
#AWS_SECRET_ACCESS_KEY = "aSjMcQVX412NZlV2vTTKR1FSDbQijyQPTpOcss9z"
#AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjEAcaCXVzLXdlc3QtMiJIMEYCIQCeyy4fZES9azHydEBRRbKgKKoQnEdIpHnQ6zlMYx73rwIhAO+l6UAaW6SPukiCAE1l1vAa1TpdcamO9IgEIcfw2UTfKrQCCFAQABoMMjc4MTAxMjU2NzE0Igy88wP6F7eisUuNiTcqkQIdOzz9CxcmWYlS0nVoiwQpUTBg8wIpBldRbrnUNc+sLHnvFJnslMIJerEirwXo1QGyRaSXDX64QqZ4Ey1Ni7mRpkP+wQk8TeqMYIDVj9PW/Komyv/EqPSM2gX4wRE6IuBq/mEns4SjdIyGeRf9rvQ4VxQTajrCujbJk6SHyY/LvDeTC17m/BrBnABI8FR2/wtbdmE4qlnS1cnC8/oz9uNFSAfLv2KUwqPwrZaCnaWd6oIf7lOzAH4186wbDl8gXnLK5Wx+FMyA5g8hnBNVxYlp+PnujxaMqkasZpU+xw5W9/dnGpURpWq00lhQ5LDoZcDqTHF0u6YYjW4Qsdy74VR6F7Se3Os/yMXQ9GIvl9euOBYw8e2tvgY6nAF6zXql5LYxuVlhwAHURhzvcPnhMx0XHmTrWnQa9AmoOVjx9ODyM+b0gjwRdcv5kEkIFmKIbCfjq396mLTUw+u7X6+VPxu5x4B/aiBg6QAk6/DC5xhrEZOVnFSM9deKyrd6fV8k/pL+48BGC3xGx/UlOS6Zl65KHB2gzrM8z9pvSpN9tHC8zZqO60dSZ6nhbYffbEvt4kAy+fL3IDs="
AWS_STORAGE_BUCKET_NAME = "x24142816-s3bucket"  # 생성한 버킷 이름
#AWS_S3_REGION_NAME = "us-east-1"  # 선택한 리전
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
# 파일 저장 설정
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
    'ContentDisposition': 'inline'
}

AWS_S3_FILE_OVERWRITE = False  # 동일한 파일명 업로드 시 덮어쓰기 방지
AWS_DEFAULT_ACL = None  # 기본적으로 private 상태 유지 (보안상 안전)
AWS_S3_ADDRESSING_STYLE = "path"

# AWS SNS 설정 
#AWS_ACCESS_KEY_ID = "ASIAUBQBANIFNBGR45SW"
#AWS_SECRET_ACCESS_KEY = "aSjMcQVX412NZlV2vTTKR1FSDbQijyQPTpOcss9z"
#AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjEAcaCXVzLXdlc3QtMiJIMEYCIQCeyy4fZES9azHydEBRRbKgKKoQnEdIpHnQ6zlMYx73rwIhAO+l6UAaW6SPukiCAE1l1vAa1TpdcamO9IgEIcfw2UTfKrQCCFAQABoMMjc4MTAxMjU2NzE0Igy88wP6F7eisUuNiTcqkQIdOzz9CxcmWYlS0nVoiwQpUTBg8wIpBldRbrnUNc+sLHnvFJnslMIJerEirwXo1QGyRaSXDX64QqZ4Ey1Ni7mRpkP+wQk8TeqMYIDVj9PW/Komyv/EqPSM2gX4wRE6IuBq/mEns4SjdIyGeRf9rvQ4VxQTajrCujbJk6SHyY/LvDeTC17m/BrBnABI8FR2/wtbdmE4qlnS1cnC8/oz9uNFSAfLv2KUwqPwrZaCnaWd6oIf7lOzAH4186wbDl8gXnLK5Wx+FMyA5g8hnBNVxYlp+PnujxaMqkasZpU+xw5W9/dnGpURpWq00lhQ5LDoZcDqTHF0u6YYjW4Qsdy74VR6F7Se3Os/yMXQ9GIvl9euOBYw8e2tvgY6nAF6zXql5LYxuVlhwAHURhzvcPnhMx0XHmTrWnQa9AmoOVjx9ODyM+b0gjwRdcv5kEkIFmKIbCfjq396mLTUw+u7X6+VPxu5x4B/aiBg6QAk6/DC5xhrEZOVnFSM9deKyrd6fV8k/pL+48BGC3xGx/UlOS6Zl65KHB2gzrM8z9pvSpN9tHC8zZqO60dSZ6nhbYffbEvt4kAy+fL3IDs="
#AWS_REGION = "us-east-1"  # 사용 중인 리전
SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:278101256714:x24142816-notification"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://1a03163033cb41b081e03a1cfe09181a.vfs.cloud9.us-east-1.amazonaws.com',
]

#SQS
#AWS_ACCESS_KEY_ID = 'ASIAUBQBANIFNBGR45SW'
#AWS_SECRET_ACCESS_KEY = 'aSjMcQVX412NZlV2vTTKR1FSDbQijyQPTpOcss9z'
#AWS_REGION_NAME = 'us-east-1'  # 적절한 AWS 리전으로 수정
SQS_QUEUE_URL = 'https://sqs.us-east-1.amazonaws.com/278101256714/x24142816_JiyoungKim_Queues'  # 해당 큐의 URL
