# Generated by Django 3.2.13 on 2022-08-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_zb_youtube', '0002_auto_20220517_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginconfig',
            name='playlist_id',
            field=models.CharField(blank=True, default='', help_text='Playlist id to view', max_length=100, verbose_name='Playlist Id'),
        ),
    ]
