from importlib.resources import files

banana = files()/'photos'/'banana.jpg'
beetle = files()/'photos'/'beetle.jpg'
bones = files()/'photos'/'bones.jpg'
building = files()/'photos'/'building.jpg'
buildings = files()/'photos'/'buildings.jpg'
cow = files()/'photos'/'cow.jpg'
horses = files()/'photos'/'horses.jpg'
lighthouse = files()/'photos'/'lighthouse.jpg'
magnolias = files()/'photos'/'magnolias.jpg'
mountains = files()/'photos'/'mountains.jpg'
pelican = files()/'photos'/'pelican.jpg'
scientist = files()/'photos'/'scientist.jpg'
subway = files()/'photos'/'subway.jpg'
toronto = files()/'photos'/'toronto.jpg'
woman_1 = files()/'photos'/'woman_1.jpg'
woman_2 = files()/'photos'/'woman_2.jpg'
woman_3 = files()/'photos'/'woman_3.jpg'