

# Build number part of version will be replaced by build number from Jenkins.
# For local builds the build number is 0 and the 'snapshot' is added as Local Version Identifier
import logging
__version__ = '1.0.2.14'

# The GIT commit ID and build date are generated by Jenkins when building the package
COMMIT_ID = '0da1892f61cfb1fc737e47c5ceebc30fbf91f82f'
BUILD_DATE = '2025-03-11 22:40:07'

logging.getLogger(__name__).addHandler(logging.NullHandler())
