import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_263be750a8(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_5fbfc7bdd2():spartaqube_cli.list()
@app.command()
def sparta_4a3f7fbca3():spartaqube_cli.sparta_4a3f7fbca3()
@app.command()
def sparta_46430a410a():print('Hello world!')
if __name__=='__main__':app()