
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-12T05:48:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1700b71bc0538fb9186d1f1e2ef59ad0339fb98d",
 "version": "1.32.0.post0.dev29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
